### PR TITLE
Stop unnecessary require because it breaks other rake tasks

### PR DESCRIPTION
**Pull request by morygonzalez**
As bundler tries to require the file named `gem-name/lib/gem-name.rb` which is guessed from gem's name, empty file should be located under lib directory. Otherwise bundler requires `capistrano-ikachan/lib/capistrano/ikachan.rb` and "capistrano/all" is to be required unintentionally. This is harmful when rake tasks are executed. This Pull Request stops such unintentional require by creating blank `capistrano-ikachan/lib/capistrano-ikachan.rb`.

### CODE REVIEW

**Comment by morygonzalez** [comment]
Othe capistrano plugins also locate blank file. Please look at https://github.com/capistrano/rbenv/blob/master/lib/capistrano-rbenv.rb for example.

**Comment by linyows** [comment]
Thanks~

**Comment by morygonzalez** [comment]
yatta~

**Comment by linyows** [comment]
https://github.com/linyows/capistrano-ikachan/releases/tag/v0.1.4

**Comment by morygonzalez** [comment]
azs~

**Pull request merged**
